;Bu Assembly programı, bellekteki iki farklı konumda saklanan değerleri kaybetmeden yer değiştirir.

MOV DX, 1000H    ; DX REGISTERINA 1000H YÜKLENİYOR.
MOV DS, DX       ; DS REGISTERI DX'E ATANARAK VERİ SEGMENTİ BELİRLENİYOR.
MOV BX, 0500H    ; BX REGISTERINA 0500H ADRESİ YÜKLENİYOR (X'İN ADRESİ: 10500H)
MOV SI, 0750H    ; SI REGISTERINA 0750H ADRESİ YÜKLENİYOR (Y'İN ADRESİ: 10750H)
MOV CX, [BX]     ; BX'İN İŞARET ETTİĞİ 10500H ADRESİNDEKİ DEĞERİ CX'E AL.
MOV DX, [SI]     ; SI'NİN İŞARET ETTİĞİ 10750H ADRESİNDEKİ DEĞERİ DX'E AL.
MOV [BX], DX     ; DX'TEKİ Y VERİSİNİ X'İN ADRESİNE (10500H) YAZ.
MOV [SI], CX     ; CX'TEKİ X VERİSİNİ Y'İN ADRESİNE (10750H) YAZ.
HLT              ; PROGRAMI SONLANDIR.
